// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyGWlRbTbPhjolSTE4xtDejtjnzs_msKM',
    appId: '1:185453674834:web:287a84859c214a6c477a8b',
    messagingSenderId: '185453674834',
    projectId: 'ff-pab-agnes',
    authDomain: 'ff-pab-agnes.firebaseapp.com',
    storageBucket: 'ff-pab-agnes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnH6qCKmETN3Hb_G_k-TsO0D3vzwvLEiU',
    appId: '1:185453674834:android:48e1042d9e429d7a477a8b',
    messagingSenderId: '185453674834',
    projectId: 'ff-pab-agnes',
    storageBucket: 'ff-pab-agnes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD__GPpi_EYCMJFGeRFvutyyhZG08ADc_4',
    appId: '1:185453674834:ios:015ce056bf3f5a2f477a8b',
    messagingSenderId: '185453674834',
    projectId: 'ff-pab-agnes',
    storageBucket: 'ff-pab-agnes.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD__GPpi_EYCMJFGeRFvutyyhZG08ADc_4',
    appId: '1:185453674834:ios:015ce056bf3f5a2f477a8b',
    messagingSenderId: '185453674834',
    projectId: 'ff-pab-agnes',
    storageBucket: 'ff-pab-agnes.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyGWlRbTbPhjolSTE4xtDejtjnzs_msKM',
    appId: '1:185453674834:web:ba5ff4ead2466fa1477a8b',
    messagingSenderId: '185453674834',
    projectId: 'ff-pab-agnes',
    authDomain: 'ff-pab-agnes.firebaseapp.com',
    storageBucket: 'ff-pab-agnes.appspot.com',
  );

}