// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGQTJ-AwjVr3h2G_c0iisxjQPyoLl9KtU',
    appId: '1:366916237252:web:53abb52f3181ebf453d691',
    messagingSenderId: '366916237252',
    projectId: 'agnesnotes',
    authDomain: 'agnesnotes.firebaseapp.com',
    storageBucket: 'agnesnotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjn0iOWuSivkQtQWdYEDbQH_nSFSz96jg',
    appId: '1:366916237252:android:1fa0f712eab6964753d691',
    messagingSenderId: '366916237252',
    projectId: 'agnesnotes',
    storageBucket: 'agnesnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6fkCHnA7SkSBPkux-FJK8B4Ij1L2KOoc',
    appId: '1:366916237252:ios:97eac2f243dc1fbd53d691',
    messagingSenderId: '366916237252',
    projectId: 'agnesnotes',
    storageBucket: 'agnesnotes.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6fkCHnA7SkSBPkux-FJK8B4Ij1L2KOoc',
    appId: '1:366916237252:ios:97eac2f243dc1fbd53d691',
    messagingSenderId: '366916237252',
    projectId: 'agnesnotes',
    storageBucket: 'agnesnotes.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGQTJ-AwjVr3h2G_c0iisxjQPyoLl9KtU',
    appId: '1:366916237252:web:351902b4b4e7ff8f53d691',
    messagingSenderId: '366916237252',
    projectId: 'agnesnotes',
    authDomain: 'agnesnotes.firebaseapp.com',
    storageBucket: 'agnesnotes.appspot.com',
  );

}