// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArMAJUxZDvzIYXM7NY0Dv1pPuPJvIAS8o',
    appId: '1:138403444096:web:8af4dcf68fde0d43f7bd65',
    messagingSenderId: '138403444096',
    projectId: 'notes-de742',
    authDomain: 'notes-de742.firebaseapp.com',
    databaseURL: 'https://notes-de742-default-rtdb.firebaseio.com',
    storageBucket: 'notes-de742.appspot.com',
    measurementId: 'G-L4E7ZKX2MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE60mqruf8UKznVXJX-Kz5E65KvCp8Onc',
    appId: '1:138403444096:android:c1e718be6be96c38f7bd65',
    messagingSenderId: '138403444096',
    projectId: 'notes-de742',
    databaseURL: 'https://notes-de742-default-rtdb.firebaseio.com',
    storageBucket: 'notes-de742.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9-t1pCvPTWjhuA1-g5cVdioRa9VjP1PI',
    appId: '1:138403444096:ios:d3910894a6a5316bf7bd65',
    messagingSenderId: '138403444096',
    projectId: 'notes-de742',
    databaseURL: 'https://notes-de742-default-rtdb.firebaseio.com',
    storageBucket: 'notes-de742.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9-t1pCvPTWjhuA1-g5cVdioRa9VjP1PI',
    appId: '1:138403444096:ios:d3910894a6a5316bf7bd65',
    messagingSenderId: '138403444096',
    projectId: 'notes-de742',
    databaseURL: 'https://notes-de742-default-rtdb.firebaseio.com',
    storageBucket: 'notes-de742.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArMAJUxZDvzIYXM7NY0Dv1pPuPJvIAS8o',
    appId: '1:138403444096:web:6aa3f20055a1d180f7bd65',
    messagingSenderId: '138403444096',
    projectId: 'notes-de742',
    authDomain: 'notes-de742.firebaseapp.com',
    databaseURL: 'https://notes-de742-default-rtdb.firebaseio.com',
    storageBucket: 'notes-de742.appspot.com',
    measurementId: 'G-6DECYVZ5CY',
  );

}